name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  actions: read
  repository-projects: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      actions: read
      repository-projects: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true


      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Project Setup
        run: ./scripts/setup.sh


      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: uv run playwright install --with-deps chromium

      - name: Install Playwright System Dependencies
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: uv run playwright install-deps chromium

      - name: Run Linting
        run: uv run ruff check .

      - name: Run Tests with Coverage
        run: uv run pytest --cov=src/pdum/gcp --cov-report=xml --cov-report=term


      - name: Temporarily disable git hooks for coverage action
        run: |
          if [ -f .git/hooks/pre-commit ]; then
            mv .git/hooks/pre-commit .git/hooks/pre-commit.disabled
          fi

      - name: Coverage Comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 80
          MINIMUM_ORANGE: 70

      - name: Re-enable git hooks
        if: always()
        run: |
          if [ -f .git/hooks/pre-commit.disabled ]; then
            mv .git/hooks/pre-commit.disabled .git/hooks/pre-commit
          fi

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt
